import { pool } from "@workspace/db";

interface SeedJob {
  title: string;
  company: string;
  location: string;
  isRemote: boolean;
  jobType: string;
  salaryMin: number;
  salaryMax: number;
  description: string;
  skills: string[];
  experienceRequired: number;
  isInternship: boolean;
}

const SEED_JOBS: SeedJob[] = [
  { title: "React Frontend Developer", company: "Tata Consultancy Services", location: "Pune, Maharashtra", isRemote: false, jobType: "fulltime", salaryMin: 600000, salaryMax: 1400000, description: "Build responsive web applications with React, Redux and TypeScript for enterprise banking clients. Strong knowledge of modern CSS and API integration required.", skills: ["react", "javascript", "typescript", "html", "css", "git"], experienceRequired: 2, isInternship: false },
  { title: "Python Backend Developer", company: "Infosys", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 800000, salaryMax: 1800000, description: "Design REST APIs and microservices in Python (Django/FastAPI). Work with PostgreSQL and Redis. Opportunity to grow into an AI/ML engineer track.", skills: ["python", "django", "sql", "redis", "docker", "aws"], experienceRequired: 3, isInternship: false },
  { title: "Full Stack Developer (MERN)", company: "Zoho", location: "Chennai, Tamil Nadu", isRemote: false, jobType: "fulltime", salaryMin: 700000, salaryMax: 1600000, description: "Own features end to end with MongoDB, Express, React and Node.js. Join a product-first team building SaaS for global customers.", skills: ["javascript", "react", "node.js", "mongo.db", "express", "git"], experienceRequired: 2, isInternship: false },
  { title: "Java Spring Boot Developer", company: "Wipro", location: "Hyderabad, Telangana", isRemote: false, jobType: "fulltime", salaryMin: 700000, salaryMax: 1500000, description: "Develop enterprise applications with Java 17, Spring Boot, and REST APIs. Work on payment systems for major Indian banks.", skills: ["java", "spring", "sql", "microservices", "git"], experienceRequired: 3, isInternship: false },
  { title: "Data Analyst", company: "Flipkart", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 600000, salaryMax: 1300000, description: "Analyze e-commerce sales data, build dashboards in Power BI and Tableau, and present insights to category teams. Strong SQL and Excel skills needed.", skills: ["sql", "excel", "tableau", "powerbi", "data science", "python"], experienceRequired: 1, isInternship: false },
  { title: "Machine Learning Engineer", company: "Amazon", location: "Hyderabad, Telangana", isRemote: false, jobType: "fulltime", salaryMin: 2000000, salaryMax: 4000000, description: "Build and deploy ML models at scale using Python, PyTorch and AWS SageMaker. Experience with NLP or computer vision is a plus.", skills: ["machine learning", "python", "aws", "data science", "docker", "sql"], experienceRequired: 4, isInternship: false },
  { title: "DevOps Engineer", company: "HCL Technologies", location: "Noida, Uttar Pradesh", isRemote: false, jobType: "fulltime", salaryMin: 900000, salaryMax: 2000000, description: "Manage CI/CD pipelines with Jenkins and GitHub Actions, containerize services with Docker and Kubernetes, and automate infrastructure with Terraform on AWS.", skills: ["devops", "docker", "kubernetes", "aws", "linux", "git"], experienceRequired: 3, isInternship: false },
  { title: "Quality Assurance Engineer", company: "Cognizant", location: "Chennai, Tamil Nadu", isRemote: false, jobType: "fulltime", salaryMin: 450000, salaryMax: 1100000, description: "Automate web and API testing with Selenium and Cypress. Write test plans, track defects in Jira, and work closely with developers.", skills: ["testing", "selenium", "sql", "jira", "python"], experienceRequired: 1, isInternship: false },
  { title: "UI/UX Designer", company: "Freshworks", location: "Chennai, Tamil Nadu", isRemote: false, jobType: "fulltime", salaryMin: 600000, salaryMax: 1400000, description: "Design intuitive SaaS interfaces in Figma. Conduct user research, create wireframes and prototypes, and maintain a design system.", skills: ["ui/ux", "design", "figma", "html", "css"], experienceRequired: 2, isInternship: false },
  { title: "Digital Marketing Executive", company: "Nykaa", location: "Mumbai, Maharashtra", isRemote: false, jobType: "fulltime", salaryMin: 400000, salaryMax: 900000, description: "Run Google Ads and Meta campaigns for beauty brands. Optimize SEO, manage social media calendars, and report on ROAS weekly.", skills: ["marketing", "seo", "email", "content", "excel"], experienceRequired: 1, isInternship: false },
  { title: "Content Writer (Technical)", company: "BrowserStack", location: "Mumbai, Maharashtra", isRemote: true, jobType: "fulltime", salaryMin: 500000, salaryMax: 1100000, description: "Write technical tutorials, blog posts and documentation for developers. Basic understanding of coding concepts required.", skills: ["content", "seo", "javascript", "html", "communication"], experienceRequired: 1, isInternship: false },
  { title: "HR Recruiter", company: "Tech Mahindra", location: "Pune, Maharashtra", isRemote: false, jobType: "fulltime", salaryMin: 350000, salaryMax: 800000, description: "End-to-end recruitment for IT roles: sourcing, screening, scheduling interviews and offer management. Excellent communication skills required.", skills: ["hr", "communication", "excel"], experienceRequired: 1, isInternship: false },
  { title: "Sales Executive (B2B SaaS)", company: "Chargebee", location: "Chennai, Tamil Nadu", isRemote: false, jobType: "fulltime", salaryMin: 500000, salaryMax: 1200000, description: "Generate and close B2B SaaS deals with Indian and SEA startups. Strong negotiation and CRM (Salesforce) skills.", skills: ["sales", "salesforce", "communication", "excel"], experienceRequired: 1, isInternship: false },
  { title: "Accountant", company: "Deloitte", location: "Gurugram, Haryana", isRemote: false, jobType: "fulltime", salaryMin: 450000, salaryMax: 1000000, description: "Handle books of accounts, GST and TDS compliance, and month-end closings. CA-inter or M.Com preferred.", skills: ["finance", "excel", "tally"], experienceRequired: 2, isInternship: false },
  { title: "Android Developer (Kotlin)", company: "Paytm", location: "Noida, Uttar Pradesh", isRemote: false, jobType: "fulltime", salaryMin: 1000000, salaryMax: 2200000, description: "Build high-performance Android apps in Kotlin with Jetpack Compose. Experience with payment SDKs is a plus.", skills: ["mobile", "kotlin", "android", "java", "git"], experienceRequired: 3, isInternship: false },
  { title: "iOS Developer (Swift)", company: "Razorpay", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 1200000, salaryMax: 2600000, description: "Develop iOS fintech applications in Swift and SwiftUI. Familiarity with Apple Pay and secure coding practices.", skills: ["mobile", "swift", "ios", "git"], experienceRequired: 3, isInternship: false },
  { title: "Cloud Engineer (AWS)", company: "Accenture", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 1000000, salaryMax: 2200000, description: "Architect and migrate workloads to AWS. Automation with Terraform, monitoring with CloudWatch, and cost optimization.", skills: ["aws", "cloud", "docker", "linux", "devops", "sql"], experienceRequired: 3, isInternship: false },
  { title: "Cyber Security Analyst", company: "Paladion Networks", location: "Hyderabad, Telangana", isRemote: false, jobType: "fulltime", salaryMin: 600000, salaryMax: 1500000, description: "Monitor SIEM alerts, perform vulnerability assessments and threat hunting. CEH or Security+ certification preferred.", skills: ["security", "linux", "network", "python"], experienceRequired: 2, isInternship: false },
  { title: "Business Analyst", company: "Capgemini", location: "Mumbai, Maharashtra", isRemote: false, jobType: "fulltime", salaryMin: 600000, salaryMax: 1400000, description: "Bridge business and engineering teams. Write BRDs, manage Jira backlogs, and run stakeholder meetings. SQL for data analysis.", skills: ["communication", "sql", "excel", "project management", "jira"], experienceRequired: 2, isInternship: false },
  { title: "Product Manager", company: "PhonePe", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 2000000, salaryMax: 4000000, description: "Own product roadmap for fintech features. Analyze user metrics, prioritize with data, and ship with engineering.", skills: ["product management", "data science", "communication", "jira", "analytics"], experienceRequired: 5, isInternship: false },
  { title: "Software Development Intern", company: "Swiggy", location: "Bangalore, Karnataka", isRemote: false, jobType: "internship", salaryMin: 240000, salaryMax: 480000, description: "3-6 month internship working on real food delivery features. Stipend 20k-40k/month. Conversion to full-time based on performance.", skills: ["javascript", "react", "node.js", "java", "python", "git"], experienceRequired: 0, isInternship: true },
  { title: "Frontend Developer Intern", company: "Meesho", location: "Bangalore, Karnataka", isRemote: true, jobType: "internship", salaryMin: 200000, salaryMax: 360000, description: "Remote internship building mobile-first web experiences. React and TypeScript experience from college projects is enough.", skills: ["react", "javascript", "typescript", "html", "css"], experienceRequired: 0, isInternship: true },
  { title: "Data Science Intern", company: "Mu Sigma", location: "Bangalore, Karnataka", isRemote: false, jobType: "internship", salaryMin: 300000, salaryMax: 500000, description: "Work on real client analytics problems with Python, SQL and ML libraries. Great stepping stone into data careers.", skills: ["python", "data science", "machine learning", "sql", "excel"], experienceRequired: 0, isInternship: true },
  { title: "Marketing Intern", company: "Zomato", location: "Gurugram, Haryana", isRemote: false, jobType: "internship", salaryMin: 180000, salaryMax: 300000, description: "Assist with campaign execution, content creation and social media for India's largest food delivery brand.", skills: ["marketing", "content", "excel", "communication"], experienceRequired: 0, isInternship: true },
  { title: "Graphic Design Intern", company: "Craftsvilla", location: "Mumbai, Maharashtra", isRemote: true, jobType: "internship", salaryMin: 150000, salaryMax: 280000, description: "Create social media creatives, banners and brand assets in Photoshop and Illustrator. Portfolio required.", skills: ["design", "photoshop", "illustrator", "figma"], experienceRequired: 0, isInternship: true },
  { title: "Full Stack Developer", company: "Ola", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 1400000, salaryMax: 3000000, description: "Work on mobility platform serving millions of daily rides. Node.js backend, React frontend, AWS infra.", skills: ["node.js", "react", "javascript", "aws", "mongo.db", "sql"], experienceRequired: 3, isInternship: false },
  { title: "Senior Data Engineer", company: "Myntra", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 1800000, salaryMax: 3500000, description: "Build data pipelines with Spark, Airflow and AWS. Ensure data quality for fashion e-commerce analytics.", skills: ["bigdata", "python", "aws", "sql", "data science"], experienceRequired: 4, isInternship: false },
  { title: "WordPress Developer", company: "BharatPe", location: "New Delhi, Delhi", isRemote: true, jobType: "fulltime", salaryMin: 500000, salaryMax: 1100000, description: "Customize WordPress themes and plugins, integrate APIs, and maintain marketing sites. PHP and SQL basics required.", skills: ["wordpress", "php", "html", "css", "javascript"], experienceRequired: 1, isInternship: false },
  { title: "Shopify Store Developer", company: "Urbanic", location: "Gurugram, Haryana", isRemote: false, jobType: "fulltime", salaryMin: 700000, salaryMax: 1500000, description: "Build custom Shopify themes and apps for a fast-growing fashion brand. Liquid, JavaScript and API skills.", skills: ["shopify", "javascript", "html", "css", "git"], experienceRequired: 2, isInternship: false },
  { title: "Technical Support Engineer", company: "Zendesk", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 500000, salaryMax: 1000000, description: "Resolve API integration issues for enterprise customers. Excellent debugging and communication skills.", skills: ["customer", "communication", "javascript", "api"], experienceRequired: 1, isInternship: false },
  { title: "SAP Consultant", company: "Infosys", location: "Pune, Maharashtra", isRemote: false, jobType: "fulltime", salaryMin: 700000, salaryMax: 1800000, description: "Implement SAP FICO/MM modules for manufacturing clients. Strong ERP process knowledge and configuration skills.", skills: ["erp", "sap", "finance", "sql"], experienceRequired: 3, isInternship: false },
  { title: "Data Entry Operator", company: "Justdial", location: "New Delhi, Delhi", isRemote: true, jobType: "parttime", salaryMin: 150000, salaryMax: 300000, description: "Remote data entry and verification tasks. High typing speed and accuracy required.", skills: ["data entry", "excel", "communication"], experienceRequired: 0, isInternship: false },
  { title: "Customer Support Executive", company: "Airbnb India", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 350000, salaryMax: 700000, description: "Resolve host and guest issues via chat and email. Night shifts possible. Training provided.", skills: ["customer", "communication", "excel"], experienceRequired: 0, isInternship: false },
  { title: "Operations Manager", company: "Blinkit", location: "Gurugram, Haryana", isRemote: false, jobType: "fulltime", salaryMin: 1200000, salaryMax: 2500000, description: "Run dark-store operations across a cluster of cities. Optimize delivery metrics and manage 50+ staff.", skills: ["operations", "leadership", "excel", "communication"], experienceRequired: 4, isInternship: false },
  { title: "Mobile App Developer (Flutter)", company: "CRED", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 1600000, salaryMax: 3500000, description: "Build delightful fintech experiences in Flutter for iOS and Android. Strong Dart and state management skills.", skills: ["mobile", "flutter", "dart", "git", "firebase"], experienceRequired: 3, isInternship: false },
  { title: "React Native Developer", company: "Groww", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 1400000, salaryMax: 3000000, description: "Develop cross-platform investing app with React Native. Deep JavaScript and mobile performance knowledge.", skills: ["mobile", "react native", "javascript", "react", "git"], experienceRequired: 3, isInternship: false },
  { title: "Node.js Developer", company: "PayU", location: "Gurugram, Haryana", isRemote: false, jobType: "fulltime", salaryMin: 1000000, salaryMax: 2200000, description: "Build payment APIs processing millions of transactions daily. Strong Node.js, Redis and SQL skills.", skills: ["node.js", "javascript", "redis", "sql", "aws"], experienceRequired: 3, isInternship: false },
  { title: "Angular Developer", company: "LTIMindtree", location: "Chennai, Tamil Nadu", isRemote: false, jobType: "fulltime", salaryMin: 500000, salaryMax: 1200000, description: "Develop banking dashboards with Angular, RxJS and TypeScript. Knowledge of PrimeNG and unit testing.", skills: ["angular", "typescript", "javascript", "html", "css", "git"], experienceRequired: 2, isInternship: false },
  { title: "Vue.js Developer", company: "ShareChat", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 900000, salaryMax: 2000000, description: "Build social media features with Vue 3 and Pinia. Experience with SSR (Nuxt) is a bonus.", skills: ["vue", "javascript", "html", "css", "node.js"], experienceRequired: 2, isInternship: false },
  { title: "Data Engineer", company: "Swiggy", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 1600000, salaryMax: 3200000, description: "Design streaming and batch data pipelines for food delivery analytics. Kafka, Spark, Airflow experience.", skills: ["bigdata", "python", "java", "sql", "aws", "devops"], experienceRequired: 3, isInternship: false },
  { title: "Site Reliability Engineer", company: "MakeMyTrip", location: "Gurugram, Haryana", isRemote: false, jobType: "fulltime", salaryMin: 1500000, salaryMax: 3000000, description: "Keep booking systems 99.99% available. SRE on Kubernetes, Terraform and Datadog.", skills: ["devops", "kubernetes", "aws", "linux", "python", "terraform"], experienceRequired: 4, isInternship: false },
  { title: "Security Engineer", company: "One97 (Paytm)", location: "Noida, Uttar Pradesh", isRemote: false, jobType: "fulltime", salaryMin: 1400000, salaryMax: 2800000, description: "Penetration test web and mobile fintech applications, manage bug bounties, and implement WAF rules.", skills: ["security", "python", "linux", "network"], experienceRequired: 3, isInternship: false },
  { title: "Data Scientist", company: "Tiger Analytics", location: "Chennai, Tamil Nadu", isRemote: false, jobType: "fulltime", salaryMin: 1200000, salaryMax: 2800000, description: "Solve forecasting and recommendation problems for retail clients using Python, scikit-learn and XGBoost.", skills: ["data science", "machine learning", "python", "sql", "excel"], experienceRequired: 2, isInternship: false },
  { title: "SEO Specialist", company: "Naukri.com", location: "Noida, Uttar Pradesh", isRemote: false, jobType: "fulltime", salaryMin: 400000, salaryMax: 900000, description: "Grow organic traffic for India's largest jobs portal. Technical SEO, backlinks and content strategy.", skills: ["seo", "marketing", "content", "analytics", "excel"], experienceRequired: 1, isInternship: false },
  { title: "Email Marketing Specialist", company: "Lenskart", location: "Gurugram, Haryana", isRemote: false, jobType: "fulltime", salaryMin: 500000, salaryMax: 1100000, description: "Own lifecycle email campaigns, A/B testing, and automation flows in Mailchimp/Klaviyo.", skills: ["email", "marketing", "content", "analytics", "excel"], experienceRequired: 1, isInternship: false },
  { title: "HR Business Partner", company: "Deloitte", location: "Hyderabad, Telangana", isRemote: false, jobType: "fulltime", salaryMin: 1000000, salaryMax: 2000000, description: "Partner with consulting practice leadership on hiring, performance and engagement. MBA HR preferred.", skills: ["hr", "communication", "leadership", "excel"], experienceRequired: 4, isInternship: false },
  { title: "Inside Sales Representative", company: "Zoho", location: "Chennai, Tamil Nadu", isRemote: true, jobType: "fulltime", salaryMin: 400000, salaryMax: 900000, description: "Remote inside sales for Zoho suite of products. Target-driven with strong communication skills.", skills: ["sales", "communication", "crm", "excel"], experienceRequired: 0, isInternship: false },
  { title: "Finance Executive", company: "HDFC Bank", location: "Mumbai, Maharashtra", isRemote: false, jobType: "fulltime", salaryMin: 500000, salaryMax: 1200000, description: "Prepare MIS reports, reconcile GL accounts, and support audits. CA-Inter or MBA Finance preferred.", skills: ["finance", "excel", "communication"], experienceRequired: 2, isInternship: false },
  { title: "Blockchain Developer", company: "Polygon", location: "Bangalore, Karnataka", isRemote: true, jobType: "fulltime", salaryMin: 2000000, salaryMax: 4500000, description: "Build smart contracts and dApps on Ethereum and Polygon. Solidity, web3.js and DeFi experience.", skills: ["blockchain", "solidity", "javascript", "python", "git"], experienceRequired: 3, isInternship: false },
  { title: "Tableau Developer", company: "Genpact", location: "Kolkata, West Bengal", isRemote: false, jobType: "fulltime", salaryMin: 800000, salaryMax: 1800000, description: "Create executive dashboards in Tableau connecting to SQL warehouses. Strong data storytelling.", skills: ["tableau", "sql", "data science", "excel"], experienceRequired: 3, isInternship: false },
  { title: "Power BI Developer", company: "EY", location: "Kolkata, West Bengal", isRemote: false, jobType: "fulltime", salaryMin: 700000, salaryMax: 1600000, description: "Build Power BI reporting solutions with DAX and data modeling for audit analytics teams.", skills: ["powerbi", "sql", "excel", "data science"], experienceRequired: 2, isInternship: false },
  { title: "Project Manager (IT)", company: "Cognizant", location: "Pune, Maharashtra", isRemote: false, jobType: "fulltime", salaryMin: 1400000, salaryMax: 2600000, description: "Lead Agile delivery of enterprise software programs. PMP/CSM certified with client management experience.", skills: ["project management", "agile", "scrum", "jira", "communication", "leadership"], experienceRequired: 6, isInternship: false },
  { title: "Product Designer", company: "Razorpay", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 1500000, salaryMax: 3000000, description: "Design end-to-end fintech product flows in Figma. Portfolio with B2B SaaS work required.", skills: ["ui/ux", "design", "figma", "prototype"], experienceRequired: 3, isInternship: false },
  { title: "Community Manager", company: "Mensa Brands", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 400000, salaryMax: 800000, description: "Manage online communities on Instagram, Discord and Reddit for D2C brands. Content creation skills.", skills: ["marketing", "content", "social media", "communication"], experienceRequired: 1, isInternship: false },
  { title: "QA Automation Engineer", company: "Mphasis", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 600000, salaryMax: 1400000, description: "Automate E2E tests with Cypress and API tests with Postman. CI integration in Jenkins.", skills: ["testing", "cypress", "javascript", "sql", "jenkins"], experienceRequired: 2, isInternship: false },
  { title: "Salesforce Developer", company: "Accenture", location: "Hyderabad, Telangana", isRemote: false, jobType: "fulltime", salaryMin: 1000000, salaryMax: 2200000, description: "Develop custom Salesforce solutions with Apex, LWC and integrations. Salesforce certified preferred.", skills: ["salesforce", "java", "javascript", "sql", "cloud"], experienceRequired: 2, isInternship: false },
  { title: "Junior Frontend Developer", company: "Unacademy", location: "Bangalore, Karnataka", isRemote: false, jobType: "fulltime", salaryMin: 400000, salaryMax: 900000, description: "Entry-level role for fresh graduates. Build UI components in React with mentorship from senior engineers.", skills: ["react", "javascript", "html", "css", "git"], experienceRequired: 0, isInternship: false },
  { title: "Frontend Developer", company: "Directi", location: "Mumbai, Maharashtra", isRemote: false, jobType: "fulltime", salaryMin: 1000000, salaryMax: 2200000, description: "Build high-performance advertising products with React and TypeScript. Web performance focus.", skills: ["react", "typescript", "javascript", "html", "css"], experienceRequired: 2, isInternship: false },
  { title: "Java Developer (Fresher)", company: "Capgemini", location: "Mumbai, Maharashtra", isRemote: false, jobType: "fulltime", salaryMin: 350000, salaryMax: 600000, description: "Fresher hiring program: 6-month paid training then placement into banking projects. Core Java and SQL required.", skills: ["java", "sql", "spring", "git"], experienceRequired: 0, isInternship: false },
  { title: "Digital Marketing Analyst", company: "PolicyBazaar", location: "Gurugram, Haryana", isRemote: false, jobType: "fulltime", salaryMin: 500000, salaryMax: 1100000, description: "Analyze paid marketing funnels, run A/B tests, and optimize ROAS using Google Analytics and Excel.", skills: ["marketing", "analytics", "excel", "seo"], experienceRequired: 1, isInternship: false },
];

export async function seedJobsIfEmpty(): Promise<{ seeded: number; skipped: boolean }> {
  const { rows } = await pool.query("SELECT count(*)::int AS c FROM jobs");
  if (Number(rows[0]?.c ?? 0) > 0) return { seeded: 0, skipped: true };
  let seeded = 0;
  for (const j of SEED_JOBS) {
    try {
      await pool.query(
        `INSERT INTO jobs (title, company, location, is_remote, job_type, salary_min, salary_max, description, skills, experience_required, is_internship, source)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'platform')
         ON CONFLICT DO NOTHING`,
        [j.title, j.company, j.location, j.isRemote, j.jobType, j.salaryMin, j.salaryMax, j.description, JSON.stringify(j.skills), j.experienceRequired, j.isInternship],
      );
      seeded++;
    } catch { /* per-row error ignored */ }
  }
  return { seeded, skipped: false };
}
