import { Router, type IRouter } from "express";
import { optionalAuth } from "../middlewares/auth.js";
import healthRouter from "./health.js";
import usersRouter from "./users.js";
import resumesRouter from "./resumes.js";
import coverLettersRouter from "./cover_letters.js";
import interviewRouter from "./interview.js";
import paymentsRouter from "./payments.js";
import adminRouter from "./admin.js";
import statsRouter from "./stats.js";
import googleRouter from "./google.js";
import notificationsRouter from "./notifications.js";
import careerRouter from "./career.js";
import resumeIntelligenceRouter from "./resume_intelligence.js";
import jobsRouter from "./jobs.js";
import resumeTailoringRouter from "./resume_tailoring.js";
import interviewCoachRouter from "./interview_coach.js";
import careerRoadmapRouter from "./career_roadmap.js";
import portfoliosRouter from "./portfolios.js";
import linkedinRouter from "./linkedin.js";
import salaryNegotiationRouter from "./salary_negotiation.js";
import weeklyReportRouter from "./weekly_report.js";
import assistantRouter from "./assistant.js";
import jobIntelligenceRouter from "./job_intelligence.js";
import subscriptionsRouter from "./subscriptions.js";

const router: IRouter = Router();

router.use(optionalAuth);

router.use(healthRouter);
router.use(usersRouter);
router.use(resumesRouter);
router.use(coverLettersRouter);
router.use(interviewRouter);
router.use(paymentsRouter);
router.use(adminRouter);
router.use(statsRouter);
router.use(googleRouter);
router.use(notificationsRouter);
router.use(careerRouter);
router.use(resumeIntelligenceRouter);
router.use(jobsRouter);
router.use(resumeTailoringRouter);
router.use(interviewCoachRouter);
router.use(careerRoadmapRouter);
router.use(portfoliosRouter);
router.use(linkedinRouter);
router.use(salaryNegotiationRouter);
router.use(weeklyReportRouter);
router.use(assistantRouter);
router.use(jobIntelligenceRouter);
router.use(subscriptionsRouter);

export default router;
